
# pods
apiVersion: v1  # string
kind: Pod       # string
metadata:        # Dict
  name: myapp-pod
  labels:         # Dict
    app: myapp

spec:
  containers:      # List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80

---

# node port 
apiVersion: v1  # string
kind: Service      # string
metadata:        # Dict
  name: myapp-pod-nodeport-service
  labels:         # Dict
    app: myapp-nodeport

spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      port: 80  # service port
      targetPort: 80  # container port
      NodePort: 31231  # nodeport