apiVersion: v1  # string
kind: Pod       # string
metadata:        # Dict
  name: myapp-pod
  labels:         # Dict
    app: myapp

spec:
  containers:      # List
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80