apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs
  labels: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2   ## should be same as myapp2 label in template metadata
  template:
    metadata:        # Dict
      name: myapp2-pod
      labels:         # Dict
        app: myapp2
    spec:
      containers:      # List
        - name: myapp2-container
          image: stacksimplify/kubenginx:2.0.0
          ports:
            - containerPort: 80      

---

apiVersion: v1  # string
kind: Service      # string
metadata:        # Dict
  name: myapp2-rs-nodeport-service
  labels:         # Dict
    app: myapp2-nodeport

spec:
  type: NodePort
  selector:
    app: myapp2
  ports:
    - name: http
      port: 80  # service port
      targetPort: 80  # container port
      nodePort: 31231  # nodeport